### ISSUE TITLE
go get 获取到的版本为v1.2.1

### ISSUE THREAD

**Issue by crunl** [unti-io/go-utils#1]
go version: go1.20.4

go get 获取到的版本为v1.2.1，v1.2.1依赖包未包含FileCacheClientItem、FileCacheClient结构体类型，导致github.com/unti-io/unti项目依赖出现问题，请维护者提交一下最新代码的Release🤪

**Comment by inis-io** [comment]
已经是最新的了，截图我看一下你的报错
